### ISSUE TITLE
Multiple simultaneous ping do not work

### ISSUE THREAD

**Issue by GoodMirek** [Microsoft/BashOnWindows#1296]
- A brief description
  Opening a powershell admin window, running bash and then running ping works fine. Opening second window the same way, while keeping the first window opened with running ping, and running another ping in the second window causes errors in both windows.
- Expected results
  Multiple pings shall work simultaneously.
- Actual results (with terminal output if applicable)

```
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
ping: recvmsg: Invalid argument
```
- Your Windows build number
  14393.351
- Steps / All commands required to reproduce the error from a brand new installation 
1. 
   Open powershell admin window1
2. 
   Run `bash` in window1
3. 
   Run `ping google.com` in window1
4. 
   Open powershell admin window2
5. 
   Run `bash` in window2
6. Run `ping google.com` in window2; running `ping time.nist.gov` produces the same result
- Strace of the failing command
- Required packages and commands to install
  WSL

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by afinnell** [comment]
@GoodMirek I realize this in no way helps your current build of Windows; but I do not experience this issue running on build 14955. Perhaps someone else can confirm this is a problem with your build of Windows and not on 14955.

**Comment by therealkenc** [comment]
Guessing this was quietly addressed in [14926](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14926), though I don't think there is/was an issue# for the problem specifically.

**Comment by benhillis** [comment]
@therealkenc I'm still able to reproduce this on new builds, there's still an issue here.  Tagging @sunilmut so he is aware.

**Comment by sunilmut** [comment]
@GoodMirek Thanks for reporting the issue and thanks @benhillis for tagging. It looks like this is reproducible even with a single ping. I have opened a bug to track this.

**Comment by GoodMirek** [comment]
After upgrade to 14955 I can confirm that simultaneous ping works.
However, ping occassionally reports incorrect round trip time 0.000ms, see below; correct value is above 10ms. Sometimes the incorrect value is not plain zero, but rather arounf half a millisecond. I did not use preload option of ping.
```
ping google.com
64 bytes from prg03s05-in-f14.1e100.net (172.217.23.206): icmp_seq=94 ttl=50 time=23.1 ms
64 bytes from prg03s05-in-f14.1e100.net (172.217.23.206): icmp_seq=95 ttl=50 time=25.3 ms
64 bytes from prg03s05-in-f14.1e100.net (172.217.23.206): icmp_seq=96 ttl=50 time=0.000 ms
64 bytes from prg03s05-in-f14.1e100.net (172.217.23.206): icmp_seq=97 ttl=50 time=16.1 ms
64 bytes from prg03s05-in-f14.1e100.net (172.217.23.206): icmp_seq=98 ttl=50 time=16.1 ms
64 bytes from prg03s05-in-f14.1e100.net (172.217.23.206): icmp_seq=99 ttl=50 time=16.2 ms
64 bytes from prg03s05-in-f14.1e100.net (172.217.23.206): icmp_seq=100 ttl=50 time=0.000 ms
64 bytes from prg03s05-in-f14.1e100.net (172.217.23.206): icmp_seq=101 ttl=50 time=16.1 ms
64 bytes from prg03s05-in-f14.1e100.net (172.217.23.206): icmp_seq=102 ttl=50 time=16.1 ms
64 bytes from prg03s05-in-f14.1e100.net (172.217.23.206): icmp_seq=103 ttl=50 time=0.519 ms
```

**Comment by sunilmut** [comment]
@GoodMirek - The 0ms ping issue has already been fixed and the fix barely missed the 14955 build. It should be in the next release for sure. If in the next release you are still seeing 0ms ping, do let us know. As for the `ping: recvmsg: Invalid argument` error, I think that is intermittent and still exists. Thanks for all the feedback and trying out WSL!

**Comment by russalex** [comment]
The 0ms ping fix is out in build 14986.

[14986 Release Notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14986)

**Comment by JasonLinMS** [comment]
The original issue has been fixed internally (recvmsg EINVAL)

**Comment by JasonLinMS** [comment]
Closing since this has been fixed in the Insider builds.
