### ISSUE TITLE
Unable to enter the pipe character "|" in bash

### ISSUE THREAD

**Issue by kirtapnosslin** [Microsoft/BashOnWindows#183]
Works fine in cmd.exe and powershell.exe and any other windows application.

**Comment by zadjii-msft** [comment]
@kirtapnosslin What keyboard layout/language are you using? #11, #12, #23 all seem like they could be related

**Comment by kirtapnosslin** [comment]
Hi, yes sorry didnt read those. I am using windows in english with swedish keyboard. Adding and switching to US english keyboard enabled the | character in bash. So there is a workaround ...

**Comment by benhillis** [comment]
This should be resolved in 14352, please reopen if you continue to see this behavior in that build.

**Comment by DJviolin** [comment]
The issue is still present on a freshly installed WSL and Debian on Win10 10.0.17763.316. The funny thing is, it worked fine until I added the Solarized theme with this registry file:

```reg
[HKEY_CURRENT_USER\Console]
"ColorTable00"=dword:00362b00
"ColorTable01"=dword:00969483
"ColorTable02"=dword:00756e58
"ColorTable03"=dword:00a1a193
"ColorTable04"=dword:00164bcb
"ColorTable05"=dword:00c4716c
"ColorTable06"=dword:00837b65
"ColorTable07"=dword:00d5e8ee
"ColorTable08"=dword:00423607
"ColorTable09"=dword:00d28b26
"ColorTable10"=dword:00009985
"ColorTable11"=dword:0098a12a
"ColorTable12"=dword:002f32dc
"ColorTable13"=dword:008236d3
"ColorTable14"=dword:000089b5
"ColorTable15"=dword:00e3f6fd
"ScreenColors"=dword:00000001
"PopupColors"=dword:000000f6
```

I use Hungarian keyboard with AltGr (right alt) key. The pipe "|" and "&" characters are not entered in WSL console, works fine in `cmd` and `ConEmu`, too. The Solarized theme also applied to `cmd`.

Interesting that even Ctrl+Alt combination not working for some reason. If I pressing Ctrl+Alt in WSL, then:

* Ctrl+Alt+c (which supposed to write "&") writes the letter c and Ctrl+Alt+v (which supposed to write "@") writes nothing.
* AltGr+c (which supposed to write "&") writes nothing and AltGr+v (which supposed to write "@") writes @ as it should! strange!

Please reopen this issue, because I think something is still messing with international users.

**Comment by icorne** [comment]
Hey DJVolin, for me it's working with a belgian keyboard
