### ISSUE TITLE
Error 0x8007001f after upgrading to Creators Update

### ISSUE THREAD

**Issue by Xyene** [Microsoft/BashOnWindows#1862]
I was really excited about trying out the new WSL features I've read about in this tracker, so I installed the Creators Update early using the update assistant. However, since doing so I can no longer launch bash, and am getting `Error 0x8007001f` whenever I try to.

I read through some older threads here and tried changing case insensitivity in the registry, as well tried launching after removing `/mnt` and `/home`, to no avail. I'm wondering if there's anything else I could try or any data I could provide before nuking WSL entirely, since I have a slow internet connection and setting up my work environment again would take a couple of days &mdash; I'd like to avoid that if at all possible.

**Comment by benhillis** [comment]
Could you double check that the Windows Subsystem for Linux (Beta) optional component checkbox is still checked?

Could you also try to remove %localappdata%\lxss\temp?

**Comment by benhillis** [comment]
Would you be able to take a trace for me?

	1. Download the below two .txt files and rename them .cmd
	2. Run start_lxcore_trace.cmd from an admin command prompt
	3. Perform the repro
	4. Run stop_lxcore_trace.cmd from an admin command prompt
	5. You should now see three .etl files in the directory where you ran the script
	6. Email the etl files to: InsiderSupport@microsoft.com. Include in the subject / message to forward to the WSL team. In the body of the email mention it is for benhill
https://github.com/Microsoft/BashOnWindows/files/288621/start_lxcore_trace.txt 
https://github.com/Microsoft/BashOnWindows/files/288622/stop_lxcore_trace.txt

**Comment by Xyene** [comment]
Work caught up to me so I had to put this on the backburner for a bit, but now that I was going to take a trace and the issue appears to have disappeared. I can't think of anything in particular I did, apart from a general restart of my system. I know I had a couple of symlinks from `/mnt` into `/mnt/c` folders that I removed, but I've since added them back identically and everything continues to work.

If it pops up again, I'll be sure to get a trace promptly.

**Comment by SAprelov** [comment]
Same problem. Creators Update via update assistant.

**Comment by TheSIlentLink** [comment]
I have the same issue and used the update assistant as well

**Comment by TheSIlentLink** [comment]
[repro.zip](https://github.com/Microsoft/BashOnWindows/files/922305/repro.zip)

I ran them and here are the 4 files

**Comment by benhillis** [comment]
@TheSIlentLink - thank you very much! I'll take a look at the traces today and see what I can find.

**Comment by benhillis** [comment]
@TheSIlentLink - I took a look at your trace files and unfortunately there are no events.  Did you start the trace, try to install, then end the trace?

**Comment by TheSIlentLink** [comment]
My bad I didn't run the install will do it again sorry

**Comment by benhillis** [comment]
No problem at all, thank you very much for the help!

**Comment by TheSIlentLink** [comment]
[repro_new.zip](https://github.com/Microsoft/BashOnWindows/files/922563/repro_new.zip)

Try this one!

**Comment by benhillis** [comment]
@TheSIlentLink - That worked, thanks! We're failing to mount one of the volumes on your machine, but there's not enough information in the trace to tell me which one is failing.

Could you give me a little bit of information about the configuration of the drives on your machine?  Do you have any non-fixed NTFS drives?

Could you share the output of the below command?
1. Run `diskpart` from an Admin command prompt
2. Run `list volume`

**Comment by TheSIlentLink** [comment]
DISKPART> list volume

  Volume ###  Ltr  Label        Fs     Type        Size     Status     Info
  ----------  ---  -----------  -----  ----------  -------  ---------  --------
  Volume 0     D                       Partition    931 GB  Healthy
  Volume 1     C                NTFS   Partition     58 GB  Healthy    Boot
  Volume 2         Recovery     NTFS   Partition    450 MB  Healthy    Hidden
  Volume 3                      FAT32  Partition    100 MB  Healthy    System

**Comment by benhillis** [comment]
Can you tell me more about your "D" volume?  It's odd that a file system type is not showing up.

**Comment by TheSIlentLink** [comment]
It is a 1TB drive formatted as NTFS

**Comment by SvenGroot** [comment]
Hi @TheSIlentLink . We need to know if there's anything unusual about the storage setup on your system. Are you using any compression or encryption software? What virus scanner do you use, if any?

It's strange that the file system type is not being shown for D: in the output of diskpart. Could you provide me with the output of the following commands (run from an elevated command prompt):
icacls D:
icacls C:
fltmc instances

Thanks for helping us figure this out!

**Comment by TheSIlentLink** [comment]
I am not using any compression or encryption software. My virus scanner is Windows Defender.

**Comment by SvenGroot** [comment]
I believe the issue is that the "NT AUTHORITY\SYSTEM" account does not have access to do your D: drive, which prevents us from accessing it during instance start. Can you please give the SYSTEM account full control by running the following command:
icacls D: /grant SYSTEM:(OI)(CI)F

Please let me know if that resolves your issue. We're looking into ways to improve this situation, but in the mean time this should unblock you.

(As a side note, this missing permission is also the reason why diskpart couldn't determine the file system type.)

**Comment by TheSIlentLink** [comment]
Well it seems that the permissions on the drive were indeed messed up and so I formatted the drive. This fixed the issue.

**Comment by SvenGroot** [comment]
Thanks, I'm glad that you were able to solve the issue. Do you have any idea how your drive got into this state?

**Comment by TheSIlentLink** [comment]
Well yes I had installed some windowsapp on the D drive and then I reinstalled windows 10. I later discovered that I didn't have permission to delete the folders (They were over 20GB) so I messed around with the permissions to try and remove it with no luck. Even Linux wouldn't remove it. So I was my fault that I broke my own drive!

**Comment by Xyene** [comment]
The details @TheSIlentLink mentioned seem to broadly apply to my scenario as well: I have a D drive that used to be the main drive of an old laptop. I was having issues deleting things until I forced some ACLs, though `list volume` does show the correct filesystem type as NTFS (I only forced permissions on some massive subfolders).

This happened months before WSL was first released, though, and prior to the Creators Update I hadn't encountered any issues.

**Comment by benhillis** [comment]
@Xyene - there was a behavior change with Creators Update when mounting DrvFs volumes. Previously the driver opened handles to the root of the volume with no access (which worked even if SYSTEM didn't have permission).  In Creator's Update we open the handle with query attributes access.

**Comment by raffaeler** [comment]
@benhillis FYI if TrueCrypt mounts a volume, bash fails with 0x8007001f (I am running the Createors Update).
As soon as the volume is dismounted, it works.
I tried to give localsystem permissions with icacls but it didn't help.
I would suggest you to give a try on your machine to identify the problem.
HTH

**Comment by cyberf3ead** [comment]
I installed Windows Creator Update and received Error: 0x8007001f when I attempted to start bash. I fixed it by ensuring SYSTEM was given permissions to each volume. When bash tries to mount your drives, if SYSTEM does not have permission, it will fail. Right click each volume, select properties, select the security tab, select advanced, select add, select a principal, type SYSTEM, select check names, select ok, select full control, select OK.

**Comment by raffaeler** [comment]
As I wrote, giving the system permissions didn't fix in my case.
In any case the error should be more clear IMO. HRESULTS are good for us (developers) but definitely sucks for users.

**Comment by Xyene** [comment]
@benhillis just out of curiosity/closure, what will the fix look like?

**Comment by benhillis** [comment]
@Xyene - This will be fixed in a couple of stages. The first fix will be to skip past drives that SYSTEM does not have access to. That will make instance launch failures go away and we are backporting this fix to Creators Update.

The second fix is to move DrvFs mounting from the driver to the init daemon. This will mean that drives are mounted under your user's context so any drives your user account has access to WSL will also. This change is a little bit more involved so it will not be backported but will be available in an Insider build soon™

**Comment by SAprelov** [comment]
I have interesting observation. My work machine is in a domain network. Then I use domain account with local admin privileges I have 0x8007001f, but if I use local account with admin priveleges it just works. I run this issue even on clean installation.

**Comment by sunilmut** [comment]
@all - Just an update that the first fix that @benhillis mentions above `first fix will be to skip past drives that SYSTEM does not have access to. That will make instance launch failures go away and we are backporting this fix to Creators Update.` has been approved for Creators Update servicing. We will update this thread once more when the fix is publicly released.

**Comment by benhillis** [comment]
This issue is fixed in 16193.

**Comment by mloskot** [comment]
I run into the same issue, but repeating the `lxrun /uninstall /full` command seems to solve the problem for me:

```
Microsoft Windows [Version 10.0.16299.192]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>lxrun /uninstall /full
Warning: lxrun.exe is only used to configure the legacy Windows Subsystem for Linux distribution.
Distributions can be installed by visiting the Windows Store:
https://aka.ms/wslstore

This will uninstall Ubuntu on Windows.
This will remove the Ubuntu environment as well as any modifications, new applications, and user data.
Type "y" to continue: y
Uninstalling...
Error: 0x80070003

C:\WINDOWS\system32>lxrun /uninstall /full
Warning: lxrun.exe is only used to configure the legacy Windows Subsystem for Linux distribution.
Distributions can be installed by visiting the Windows Store:
https://aka.ms/wslstore

This will uninstall Ubuntu on Windows.
This will remove the Ubuntu environment as well as any modifications, new applications, and user data.
Type "y" to continue: y
Uninstalling...
The Windows Subsystem for Linux has an install or uninstall operation pending.

C:\WINDOWS\system32>
```

**Comment by juso** [comment]
Hmm, probably my issue is similar, though I've opened a new [ticket ](https://github.com/Microsoft/WSL/issues/2823) already. Feel free to close my newly created ticket and copy/paste the content here.

**Comment by benranck** [comment]
I also had this problem, but it was due to my user folder being encrypted. Once I removed encryption it worked without error.
