### ISSUE TITLE
Error: 0x8007007e when running Ubuntu for WSL

### ISSUE THREAD

**Issue by nlundquist** [Microsoft/BashOnWindows#2316]
When installing Ubuntu from the Windows Store and running it for the first time (and thereafter), the following output is seen instead of starting the Ubuntu install process:
```
> ubuntu
Installing, this may take a few minutes...
Installation Failed!
Error: 0x8007007e
Press any key to continue...
```
Pressing any key drops back to the Windows shell.

I'm running the Windows 10 Pro Insider Preview Build 16193.rs_prerelease.170507-1300

Judging from the 1 star reviews on the Windows Store a number of other users are experiencing this same issue.

I haven't been able to capture any logging with more descriptive information. If any devs can advise on how I might capture more useful information I'll be glad to do so.

**Comment by benhillis** [comment]
@nlundquist - Have you enabled the Windows Subsystem for Linux optional component?

**Comment by nlundquist** [comment]
Yes the "Windows Subsystem for Linux (Beta)" option is enabled under the Windows Features control panel. I've had it enabled since before I updated to the Insider Preview builds. Would you advise uninstalling and reinstalling it?

**Comment by benhillis** [comment]
@nlundquist - you should not need to.  Could you please collect a trace for me?

https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md#8-detailed-logs

**Comment by nlundquist** [comment]
I've run those commands prior to running `unbuntu` and ended up with the following output after stopping:
[logman.zip](https://github.com/Microsoft/BashOnWindows/files/1140192/logman.zip)

Didn't see anything of relevance in the output but perhaps I wasn't reading them correctly.

**Comment by benhillis** [comment]
@nlundquist - Thanks for collecting the logs.  Unfortunately there aren't any data points in them which means that things are falling over before it gets to our component...  Could you double check that the optional component is still enabled?  There is a bug that will occasionally disable optional components on build upgrade.

**Comment by nlundquist** [comment]
Hmm interesting. I'm certain the WSL feature is enabled (or at least appears to be):
![features](https://user-images.githubusercontent.com/2623867/28090532-e053d8b4-6649-11e7-8073-4cee6e5cf823.gif)

and the Windows bash shell still works as expected:
![shell](https://user-images.githubusercontent.com/2623867/28090642-3357c926-664a-11e7-8df0-2256ba10c032.gif)

**Comment by benhillis** [comment]
Yeah this might be related to the Store API's.  Adding some of the folks that worked on the Store API's here to see if they have any idea how to diagnose this further. @bitcrazed @paulcam206 @zadjii-msft.

Can you think of anything "special" about your machine, any settings relevant to store apps that you may have changed?

**Comment by nlundquist** [comment]
I've checked for the above binaries and `%windir%\System32\wslapi.dll` is missing. The rest of the binaries are present. This may be the culprit? No idea how this one .dll could be missing though.

Can't think of anything particularly out of the ordinary about my system configuration. Standard paths for everything. Most unusual thing may be that I have Docker installed.

**Comment by benhillis** [comment]
I spoke with the dev lead for the Windows console and it appears that the appx that was submitted to the store has the wrong minimum version number.  Installing the store application requires build 16203 or later (you are running 16193).

Sorry for the inconvenience, but the good news is as soon as you upgrade to your next insider build things should be good.

**Comment by nlundquist** [comment]
Ahh I'll give that a shot and report back.

**Comment by benhillis** [comment]
@nlundquist - Thank you very much for your help!

**Comment by bitcrazed** [comment]
@nlundquist - Thanks for reporting & for your help diagnosing this snafu. We're working to remedy this with our partners too.

Just goes to show that we're not kidding when we say that we can't make WSL awesome without the help and support of our community 😀

**Comment by nbantatua** [comment]
This happened to me as well but I'm on OS build 16237.1001

I found out that restarting after ticking `Windows Subsystem for Linux` from `Windows Features` doesn't install anything at first try, well at least to my experience. 

It took me two un-tick/tick attempts before it installed anything upon restart and made the bash terminal to work.

**Comment by nlundquist** [comment]
I've confirmed this is fixed when I'm on 16232. This issue can be closed imo.

**Comment by andreujuanc** [comment]
@benhillis @nlundquist I just installed 16232 and had the same issue.  So probably not fixed here.

**Comment by spotlightishere** [comment]
This happened with me, even on a newer build as mentioned above.

I installed Windows 10 yesterday (no idea build) and immediately upgraded to build 16241. In my case I went to the store and installed the Ubuntu tile, and received the same error. When I went to features WSL wasn't even enabled despite the tile being available. Upon manually enabling it worked as expected.

**Comment by nlundquist** [comment]
@spotlightishere yeah the tile will appear even if WSL isn't installed. I don't think that's a bug. WSL currently must be installed manually.  

The issue I was experiencing was that even with WSL installed I was seeing this error.

**Comment by benhillis** [comment]
We have reached out to the distribution partners and provided guidance on how to detect that the optional component is not installed.  We also have an ask our to the Windows Store team to filter or allow enabling our optional component from the store UI.

**Comment by donfanning** [comment]
Confirming the issue exists in 16257.rs3_release.170728-1700.

**Comment by mrfelker** [comment]
And the same error in a VMware WS Pro 12.5.7 VM running on Debian Sid
![wsl-ubuntu-error-vmware](https://user-images.githubusercontent.com/13412724/30051855-885042e6-91f1-11e7-84b4-f35b1d70fd63.png)

**Comment by zadjii-msft** [comment]
@mrfelker have you installed the WSL optional component?
https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

>Enable the "Windows Subsystem for Linux" optional feature and reboot.
>    Open PowerShell as Administrator and run:
>    `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`

**Comment by mrfelker** [comment]
No, I have not.    I will do so on both the physical and virtual machines and get back to you.   Thanks

**Comment by mrfelker** [comment]
No, I have not.    I will do so on both the physical and virtual machines and get back to you.   Thanks

**Comment by mrfelker** [comment]
Same error on the server
![wsl-ubuntu-error-vmware](https://user-images.githubusercontent.com/13412724/30086654-4ada16a2-926a-11e7-9c38-55b07fa296fe.png)

**Comment by benhillis** [comment]
@mrfelker - You will need to enable the Windows Subsystem for Linux optional component and reboot your machine.  Have you done that?

**Comment by mrfelker** [comment]
This is working on VM!.  I will recheck the server (it is possible I didn't type the command correctly.  Will see if I can cut and paste to rememina
![wsl-ubuntu-sucess-vmware](https://user-images.githubusercontent.com/13412724/30087038-4610abfc-926c-11e7-9b2a-b028e7546b6f.png)

**Comment by mrfelker** [comment]
And now it works on the server as well.   Thank you very much for pointing this out.  I hope that's all that the other posters needed to do
![wsl-ubuntu-success-hp](https://user-images.githubusercontent.com/13412724/30087972-c16e9c6e-9271-11e7-9b8c-a0dce36e59d5.png)

**Comment by catherineedwards** [comment]
Just letting you know that I encountered this same issue today after getting the Ubuntu install package from the Windows store.

**Comment by JackRBlack** [comment]
same issue in 16299.15. I have already enabled the windows subsystem for Linux.

**Comment by bitcrazed** [comment]
@JackRBlack - Could you open a CMD prompt and type enter Ubuntu.exe (or whichever distro you're using) and paste a screenshot?

**Comment by JackRBlack** [comment]
@bitcrazed Sure. Please check the following screenshots.

![cmd](https://user-images.githubusercontent.com/22671074/32585688-a0eecd6a-c539-11e7-8ce9-3ad817d5bb1d.PNG)

![wsl](https://user-images.githubusercontent.com/22671074/32585734-da89690e-c539-11e7-917a-2c43e87a6614.PNG)

![build](https://user-images.githubusercontent.com/22671074/32585754-efa92108-c539-11e7-83f8-08593bef93cc.PNG)

**Comment by bitcrazed** [comment]
Thanks @JackRBlack 

Did you reboot after enabling WSL? I reboot is required because WSL must load v. early in the boot process, before any 3rd party code, in order to ensure chain of trust.

**Comment by 40smile** [comment]
1. Open PowerShell as Administrator and run:

Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
2. Restart your computer when prompted.

**Comment by karenerobinson** [comment]
Seriously canonical, what is this nonsense.  The "ubuntu" pane in the MS Store looks like a one-click install.  I am trying to get it working on a clean install of windows---one of about 10 things I need to install to get back to my normal workspace---and I'm stuck on this one.  

This is the kind of thing that gives Linux a reputation for low usability!  Thanks for everything you do to make it more usable, but REALLY: USERS SHOULD FIND OUT THAT ANOTHER INSTALL IS REQUIRED FOR IT TO WORK BEFORE TRYING TO RUN AND GETTING AN ERROR.

It's this feeling that you think you're off to the races and then some error grabs your ankles that is so frustrating.

**Comment by karenerobinson** [comment]
I just want to get a linux enviro up, it's not my fault that I'm on a windows machine, and here I am learning about the PowerShell so I can use it to install WSL so that then I can enable WSL in some mysterious windows dialog box.

shaving.  yaks.

**Comment by bitcrazed** [comment]
@karenerobinson Thanks for sharing your thoughts here. You're right - this experience can and will be improved in the future. @tara-raj & team are looking into improving the store experience in the future, reducing/eliminating points of friction like this.

In the interim, while not entirely optimal:

1. The WSL [installation docs ](https://docs.microsoft.com/en-us/windows/wsl/install-win10) do describe the step by step installation instructions
1. Canonical, SUSE etc. do state in their product description that WSL needs to be enabled before the distro can be used,  & provide instructions on how to do so:

![image](https://user-images.githubusercontent.com/961950/34120702-6d3de710-e3db-11e7-9c89-3fb118280998.png).

Thanks for sharing your experience. We look forward to continuing to work with you and the community with us to improve WSL for all our users.

**Comment by hiitiger** [comment]
I have the same issue now. Already enabled WSL feature, winver is 16299 and install Ubuntu from Windows Store still get the error
```
The WSL optional component is not enabled. Please enable it and try again.
See https://aka.ms/wslinstall for details.
Error: 0x8007007e
```

**Comment by bitcrazed** [comment]
@hiitiger did you reboot after enabling WSL? The reboot is required before WSL will run.

**Comment by jean-ls** [comment]
Unable to enable WSL
![image](https://user-images.githubusercontent.com/28815496/36561013-4392c12a-17f1-11e8-98d7-5b1aaca54fe4.png)

**Comment by bitcrazed** [comment]
@jean-ls - my sincere apologies, but I am terrible with languages: could you confirm the translation of that error message:

**Comment by TonyHenrique** [comment]
The message says:
"Could not read the key of configuration Registry"

I showed WSL to my colleague Jean (@jean-ls): WSL installation completed, asked for reboot, when we tried to install Ubuntu, it gave an error indicating WSL was not installed Then when we returned to Control Panel it was unckeched again.
Tomorrow we will put here his WinVer screenshot.

**Comment by dennisxrow** [comment]
I have the same issue as @jean-ls and @TonyHenrique 
I tried ```Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux``` in an administrator powershell and got the same error message (just in German).

```
PS C:\WINDOWS\system32> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Enable-WindowsOptionalFeature : Der Schlüssel der Konfigurationsregistrierung konnte nicht gelesen werden.
In Zeile:1 Zeichen:1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

PS C:\WINDOWS\system32>
```
Im running on a Surface 3 with Windows 10 Pro 1709 Build 16299.125

**Comment by jblythe23** [comment]
I have a similar issue as @TonyHenrique . I have tried the powershell command as administrator and tried checking the windows subsystem box and after the reboot it comes back unchecked. i have tried it more than 10 times and still cant run ubuntu.

Windows 10 Pro Version 1709 OS Build 16299.251

Please any help would be much appreciated

**Comment by marioandluigi878** [comment]
Same here would be awesome if this could get fixed

**Comment by TonyHenrique** [comment]
On my notebook, I am using latest Windows preview build and WSL just works.

![image](https://user-images.githubusercontent.com/6307623/37867958-794ff98c-2f7e-11e8-8119-a1deb3600fa4.png)

**Comment by JesseTG** [comment]
I might be hitting this issue. The error message is different, but the error *code* (0x8007007e) is the same. Details [here](https://superuser.com/questions/1718523/wsl-fails-to-start-in-windows-10-the-specified-module-could-not-be-found-er) and [here](https://github.com/microsoft/WSL/discussions/8359).
