### ISSUE TITLE
Strange behaviour with writev()

### ISSUE THREAD

**Issue by arachnist** [Microsoft/BashOnWindows#238]
I took a simple bit of code:
```C
#include <stdio.h>
#include <unistd.h>

int main(int argc, char *argv[]) {
	printf("this printf\ndoes not work\n");
	printf("this printf works\n"); 
	return 0;
}
```

Compiled it statically on a **musl** system, copied it over to the windows box and the results were interesting:
```
root@localhost:~# ./test.musl
this printf works
root@localhost:~#
```

So… what's happening here? This is what strace says:
```
root@localhost:~# strace -o test.musl.strace ./test.musl
strace: Test for PTRACE_O_TRACESYSGOOD failed, giving up using this feature.
this printf works
_exit returned!
root@localhost:~# cat test.musl.strace
execve("./test.musl", ["./test.musl"], [/* 13 vars */]) = 0
arch_prctl(ARCH_SET_FS, 0x602570)       = 0
set_tid_address(0x6025a8)               = 2381
ioctl(1, TIOCGWINSZ, {ws_row=88, ws_col=237, ws_xpixel=0, ws_ypixel=0}) = 0
writev(1, [{0x602168, 0}, {"this printf\n", 12}], 2) = -1 EFAULT (Bad address)
writev(1, [{"this printf works", 17}, {"\n", 1}], 2) = 18
exit_group(0)                           = ?
<... exit_group resumed> )              = ?
+++ exited with 0 +++
```

The `writev(1, [{0x602168, 0}, {"this printf\n", 12}], 2) = -1 EFAULT (Bad address)` line looks especially interesting.

For comparison, this is what strace on a linux box says for the exact same binary:
```
execve("./test.musl", ["./test.musl"], [/* 27 vars */]) = 0
arch_prctl(ARCH_SET_FS, 0x602570)       = 0
set_tid_address(0x6025a8)               = 4108
ioctl(1, TIOCGWINSZ, {ws_row=58, ws_col=85, ws_xpixel=850, ws_ypixel=1044}) = 0
writev(1, [{"", 0}, {"this printf\n", 12}], 2) = 12
writev(1, [{"does not work", 13}, {"\n", 1}], 2) = 14
writev(1, [{"this printf works", 17}, {"\n", 1}], 2) = 18
exit_group(0)                           = ?
+++ exited with 0 +++
```

I've attached the static musl binary in question.
[test.musl.zip](https://github.com/Microsoft/BashOnWindows/files/229093/test.musl.zip)

**Comment by benhillis** [comment]
@arachnist Thanks for reporting this, I tried running your static musl binary in our dev branch and I can confirm that I'm seeing both printf outputs.  The strace output also no longer shows a EFAULT.

The fix to the writev system call that will be making its way to the flighting branch.

**Comment by mileswu** [comment]
Is this supposed to be fixed in build 14332? Or is the fix still waiting for release? I ran into this issue on 14332, but not on 14328. I've put my logs below in case they are helpful.

### strace
```
open("out.pdf", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 16
time(NULL)                              = 1461989642
writev(16, [{"%PDF-1.4%\342\343\317\3231 0 obj<</Type /Cat"..., 8173}, {"<</Type/Pattern/Matrix[0.05 0 0 "..., 66}], 2) = 8239
brk(0xc3a000)                           = 0xc3a000
brk(0xc6a000)                           = 0xc6a000
brk(0xc5a000)                           = 0xc5a000
brk(0xc4a000)                           = 0xc4a000
brk(0xc3a000)                           = 0xc3a000
brk(0xc39000)                           = 0xc39000
write(16, " 23 0 R/PaintType 2/TilingType 1"..., 3656) = 3656
brk(0xc37000)                           = 0xc37000
close(16)                               = 0
```
I don't see the EFAULT though.

### Output
```
root@DESKTOP-8RJENQP:~/root# head out.pdf 
23 0 R/PaintType 2/TilingType 1/BBox[0 0 100 100]/XStep 100/YStep 100/Length 122/Filte
```
It seems like the first `writev()` didn't do anything as the `%PDF-4.1` that should be at the beginning of the file is missing.

### Code extract
```
fStream = new ofstream(); 
fStream->open(fname, ofstream::out); 
while(...) {
	// Writes contents of PDF here
	fStream->write(fBuffer, fLenBuffer);
}
```
It just uses standard C++ to write to an `ofstream`.

**Comment by benhillis** [comment]
No the fix for this is not in 14332.  Keep an eye out for the release notes as we release new builds and I'll make sure this fix gets called out in them.

**Comment by eliseofe** [comment]
Hello! Is the fix in 14342 that just came out ?

**Comment by mileswu** [comment]
The program that used to exhibit the writev() bug no longer does for me in 14342, but that doesn't necessarily mean that it is fixed. For example, I didn't run into it in 14328 even though that had the bug too.

**Comment by eliseofe** [comment]
I still have issue reported at #272 . Cmake still does not find compilers.

**Comment by pbfy0** [comment]
I wrote a workaround that emulates the writev syscall using ptrace and ld_preload. It's pretty ugly, and it may not work in all cases, but it generally seems to work. You can find it at https://github.com/pbfy0/writev_fix

**Comment by benhillis** [comment]
I've verified this is fixed in 14352. Please reopen if you continue to see this issue.
