### ISSUE TITLE
Emacs has screen drawing issues in the terminal

### ISSUE THREAD

**Issue by PhilipDaniels** [Microsoft/BashOnWindows#243]
Scrolling around a file can cause display issues: sometimes characters are drawn in the wrong positions, sometimes they are not drawn. It's particularly obvious if you navigate to the end of the file then move back up and down repeatedly, hitting end of buffer. Also, Emacs does not seem to respond correctly to resizing of the terminal window. The attached animation demonstrates these issues, notice how strbuf_release appears spuriously at the end of the file after scrolling down, how some inverse video characters from the modeline appear half way up the screen on the right hand side, and how the mini-buffer seems to end up 3 lines tall when I resize the window.

![emacs terminal display issues](https://cloud.githubusercontent.com/assets/1809220/14725233/9df93ea0-0812-11e6-8b80-9bd3e3d04599.gif)

**Comment by PhilipDaniels** [comment]
If you don't want to install Emacs you can demonstrate similar problems in "tig" the terminal git browser.

**Comment by Nutzzz** [comment]
See issue #52 

TERM should probably be set to pcansi or interix
e.g.:
`export TERM=pcansi`

**Comment by bitcrazed** [comment]
We have a fix for this that's bubbling up through our build system.

**Comment by PhilipDaniels** [comment]
It's much better in Build 14332, to the point that I was not able to generate any problems by simply scrolling the file up and down. However, resizing the terminal window is still not handled properly.

**Comment by bitcrazed** [comment]
Great to hear we've addressed some of the issues you report :) We have a few more fixes on the way for resizing-related issues, coming soon to an insiders build near you 😁 

Closing for now - please reopen if you see continued issues here.

**Comment by tomjaguarpaw** [comment]
I still see Emacs drawing issues in 16299.  Do you want me to elaborate here or is there somewhere else I should go
