### ISSUE TITLE
ulimit is unlimited, compile nodejs 6.0. execvp: printf: Cannot allocate memory

### ISSUE THREAD

**Issue by sriharshav** [Microsoft/BashOnWindows#297]
make[1]: execvp: printf: Cannot allocate memory
make[1]: *** [/home/harsha/node-v6.0.0/out/Release/obj.target/deps/openssl/libopenssl.a] Error 127
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/harsha/node-v6.0.0/out'
make: *** [node] Error 2

**Comment by benhillis** [comment]
Would you be able to share a sample source file that's exhibiting this problem?

**Comment by nerogit** [comment]
+1

**Comment by sriharshav** [comment]
@benhills as mentioned it is observed while compiling nodejs.

I suspect it is related to issue on how meminfo is reported.
bash(WSL) was reporting available memory as 1GB though I got 8GB.

I updated to Build 14342 today. Now meminfo is fixed and reports properly.

But error persists

Steps to reproduce :

1. Download nodejs source
2. Extract 
3. `/configure`
4. `make -jx`

```
make[1]: execvp: printf: Cannot allocate memory
make[1]: *** [/home/harsha/node-v6.0.0/out/Release/obj.target/deps/openssl/libopenssl.a] Error 127
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/harsha/node-v6.0.0/out'
make: *** [node] Error 2
```

**Comment by benhillis** [comment]
@sriharshav Thanks, given what is printing the error message (execvp) I suspect this is actually due to some exec support that we recently added that hasn't quite made it to the fast ring yet.

**Comment by benhillis** [comment]
This should be fixed in 14352, please reopen if you continue to have issues.

**Comment by sriharshav** [comment]
@benhillis It is not solved even with 14352. It just passed through memory error and now stops with Invalid arguments.

> make[1]: execvp: printf: Invalid argument
> make[1]: *** [/home/harsha/node-v6.0.0/out/Release/obj.target/deps/openssl/libopenssl.a] Error 127
> make[1]: Leaving directory `/home/harsha/node-v6.0.0/out'
> make: *** [node] Error 2
>

**Comment by benhillis** [comment]
Ok. Reopening.

**Comment by sriharshav** [comment]
@benhillis With 14361 this issue is resolved.

**Comment by benhillis** [comment]
Thank you for confirming!
