### ISSUE TITLE
0.0.0.0 and [::] are not accepted as synonyms for localhost

### ISSUE THREAD

**Issue by cgull** [Microsoft/BashOnWindows#388]
Unlike most other TCP/IP stacks, the Linux networking stack accepts `0.0.0.0` and `::` as valid addresses in sockaddrs, and treats them as localhost.  WSL rejects these addresses.  By the relevant RFCs, Linux has an incorrect implementation, but there's probably enough bad code out there using these addresses for this to be worth fixing.

Repro:
```shell
nc -v 0 445
nc -v :: 445
```

**Comment by sunilmut** [comment]
@cgull - That's unfortunate. But, fortunately, the fix should be trivial and something that can be purely handled within WSL. I have opened a bug for it. Interesting find, thanks for reporting it! 

Out of curiosity, did you see any app failing because of this?

**Comment by cgull** [comment]
No, I don't have a purely app-based failure case for this.  I noticed it in my testing where I'd do `mosh --local 0` from the command line, which is a handy/lazy shortcut for `127.0.0.1`.

**Comment by niftyhacking** [comment]
On Tue, May 17, 2016 at 5:36 PM, cgull <notifications@github.com> wrote:

> Unlike most other TCP/IP stacks, the Linux networking stack accepts
> 0.0.0.0 and :: as valid addresses in sockaddrs, and treats them as
> localhost. WSL rejects these addresses. By the relevant RFCs, Linux has an
> incorrect implementation,
>

If Linux has an incorrect implementation there should be a Linux side bug
number.
I dislike propagation of errors.   Bug compatible is troubling and weighs
heavy
on systems.




-- 
  T o m    M i t c h e l l

**Comment by sunilmut** [comment]
@cgull - Thanks. Given that there is no app breaking on this currently, we will deprioritize this bug fix.
@niftyhacking - Ideally, yes and that would be nice too. But, as a compatibility layer, we are working more towards compat, rather than pure standards. And, if there are apps that have taken dependency on certain non-standard behavior, we are required to support it. In this particular case, we will delay the fix for this till an app is reported broken.

**Comment by cgull** [comment]
Just to be clear:  the case I'm speaking of is when these addresses are used for *remote* socket endpoints-- there's several other cases (`bind()`, routes) where usage of these addresses is correct.  I think everyone here understands this though.
@niftyhacking: as I recall, this behavior was introduced in the first Linux TCP/IP stack, and consciously maintained when it was replaced by a second one (or maybe that's second and third, can't remember).  This was all before 2000, I think.  Linux is not changing now.
@sunilmut: I don't think this is a major issue.  But you might consider logging usage of these addrs in dev/test builds to see how often they come up.

**Comment by sunilmut** [comment]
Just fyi that we have "fixed" this in WSL, in our dev branch. Should hit the release branch sometime soon. Thanks for reporting this.

**Comment by russalex** [comment]
Fixed as of [14361](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes).

**Comment by cgull** [comment]
looks good here.

**Comment by abhishek1214** [comment]
I am still facing issues with this. I have the latest build 14367

**Comment by benhillis** [comment]
@abhishek1214 Can you please clarify which part of this isn't working?  The repro from the original bug report is working from me.

```
nc -v 0 445
nc -v :: 445
```

**Comment by abhishek1214** [comment]
I use this command to start my dev server.

python manage.py runserver 0.0.0.0:8000 --settings=healthify.local_settings

This does not expose this to my ip address so that i may open my pages on my mobile phone.

**Comment by benhillis** [comment]
Have you unblocked port 8000 through the Windows firewall?

**Comment by abhishek1214** [comment]
I did that, it started working for me.

Thanks a lot. This channel has been very helpful.
