### ISSUE TITLE
 Circular directory structure warning.

### ISSUE THREAD

**Issue by yadavshubhanshu** [Microsoft/BashOnWindows#389]
Running the du command on the / directory gives me a warning "circular directory structure".  It doesn't give me that warning though if I run the same command on the home directory. Specifically, 
```
root@DESKTOP:~# cd /
root@DESKTOP:/# du -sh
du: WARNING: Circular directory structure.
This almost certainly means that you have a corrupted file system.
NOTIFY YOUR SYSTEM MANAGER.
The following directory is part of the cycle:
  ‘./cache’

du: WARNING: Circular directory structure.
This almost certainly means that you have a corrupted file system.
NOTIFY YOUR SYSTEM MANAGER.
The following directory is part of the cycle:
  ‘./data’

du: cannot access ‘./dev/adss’: Operation not permitted
du: cannot access ‘./dev/tty0’: Invalid argument
du: WARNING: Circular directory structure.
This almost certainly means that you have a corrupted file system.
NOTIFY YOUR SYSTEM MANAGER.
The following directory is part of the cycle:
  ‘./mnt’

du: cannot access ‘./proc/121/fd/3’: No such file or directory
du: cannot access ‘./proc/121/task/121/fd/3’: No such file or directory
du: WARNING: Circular directory structure.
This almost certainly means that you have a corrupted file system.
NOTIFY YOUR SYSTEM MANAGER.
The following directory is part of the cycle:
  ‘./run/lock’

du: WARNING: Circular directory structure.
This almost certainly means that you have a corrupted file system.
NOTIFY YOUR SYSTEM MANAGER.
The following directory is part of the cycle:
  ‘./run/shm’

du: WARNING: Circular directory structure.
This almost certainly means that you have a corrupted file system.
NOTIFY YOUR SYSTEM MANAGER.
The following directory is part of the cycle:
  ‘./run/user’

739M    .
```

I'm currently on windows build 14342.1000.

**Comment by benhillis** [comment]
This has been fixed internally and will be available in a future Windows Insider build.

**Comment by benhillis** [comment]
I've verified this is fixed in build 14352, please reopen if you continue to see this issue. Thanks!

**Comment by seliestel** [comment]
I am getting this same error on build 19043.1165. I tried uninstalling and reinstalling WSL, but the problem persists. It happens both with WSL1 and WSL2. The error is triggered by running 'du -sh' on any directory or trying to remove a directory with 'rm -rf'. 

```
du: WARNING: Circular directory structure.
This almost certainly means that you have a corrupted file system.
NOTIFY YOUR SYSTEM MANAGER.
The following directory is part of the cycle:
  ./old

```
I haven't been able to find any solution anywhere. Any help will be greatly appreciated.

**Comment by iSeiryu** [comment]
I get the same error but about a different directory - freshly installed Ubuntu 22.04
```bash
du: WARNING: Circular directory structure.
This almost certainly means that you have a corrupted file system.
NOTIFY YOUR SYSTEM MANAGER.
The following directory is part of the cycle:
  ./sys/kernel/debug/device_component
```

```bash
> cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
```
