### ISSUE TITLE
NPM Webpack not watching

### ISSUE THREAD

**Issue by BeneCollyridam** [Microsoft/BashOnWindows#396]
## Using node with webpack and babel

New code doesn't compile automatically. Possibly due to not enough watchers. When trying to fix this with:  

```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

I get the error:  

```
sysctl: cannot stat /proc/sys/fs/inotify/max_user_watches: No such file or directory
```

I am running Windows 10 Insider Preview Build 14342

**Comment by benhillis** [comment]
@BeneCollyridam inotify is currently not implemented (this is also brought up in #216).  Does the code you're compiling require inotify support?  If we were reporting max_user_watches = 0 would compilation continue?

**Comment by BeneCollyridam** [comment]
No, it does not require I notify. It was meant to automatically recompile when changed but I guess I'll just have to wait.

**Comment by benhillis** [comment]
@BeneCollyridam that seems very useful!  Inotify is definitely something that is on our backlog.

**Comment by michallepicki** [comment]
Related: it seems that brunch does not work at all without inotify.

**Comment by yaycmyk** [comment]
Basically anything that uses chokidar doesn't work.

**Comment by yaycmyk** [comment]
Just FYI, I landed a patch on Chokidar that will fix things for the time being. Before you run your subdependency that uses chokidar, set the environment variable `CHOKIDAR_USEPOLLING=1`.

Requires chokidar@1.6.0, but better than nothing.

**Comment by ivoviz** [comment]
@yaycmyk Although your method works, it's really not ideal. Using it will cause nodejs to use 100% cpu, sadly - at least in my case. Is there a workaround for that?

**Comment by yaycmyk** [comment]
@ivoviz Not until the proper subsystems are implemented, unfortunately.

**Comment by yaycmyk** [comment]
Take a hard look at what's being watched and try to make the patterns as narrow as possible - your watch is likely looking at more things than it needs to...

**Comment by ivoviz** [comment]
Unfortunately I can't really control what's being watched, it's been done by angular-cli. This really is a huge blocker.

**Comment by mikeesouth** [comment]
I also see this as a huge blocker for BashOnWindows. I can't get my webpack config to work at all, even if I try to remove watch and inline options. I'm using webpack-dev-server. I get many errors like this one:
```
    ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./css/site.scss
    Module build failed: Error: EINVAL: invalid argument, uv_interface_addresses
        at Error (native)
        at Object.lib.networkInterfaces (/mnt/c/Stuff/Git/showdown/node_modules/macaddress/index.js:31:21)
        at Object.lib.one (/mnt/c/Stuff/Git/showdown/node_modules/macaddress/index.js:79:26)
        at Object.<anonymous> (/mnt/c/Stuff/Git/showdown/node_modules/uniqid/index.js:15:77)
        at Module._compile (module.js:541:32)
        at Object.Module._extensions..js (module.js:550:10)
        at Module.load (module.js:458:32)
        at tryModuleLoad (module.js:417:12)
        at Function.Module._load (module.js:409:3)
        at Module.require (module.js:468:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/mnt/c/Stuff/Git/showdown/node_modules/postcss-filter-plugins/dist/index.js:9:15)
        at Module._compile (module.js:541:32)
        at Object.Module._extensions..js (module.js:550:10)
        at Module.load (module.js:458:32)
        at tryModuleLoad (module.js:417:12)
```

**Comment by wangxiexe** [comment]
yes, BashOnWindows is exciting, but without this being fixed, we just can not start our dev work with it -- just need to the watch feature ~

**Comment by kayakyakr** [comment]
This issue has been solved as of build 14942

See #216

**Comment by leafoflegend** [comment]
@mikeesouth This issue still is not solved as far as I can tell. On the newest fast-ring. uv_interface address issues are seperate from inotify. This is network enunaration. Looking for a fix to a very similar error.

**Comment by jackchammons** [comment]
@all as of build [#14946](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14942) WSL supports inotify. @BeneCollyridam please verify and then close this issue.

@mikeesouth the uv_interface_address error has also been solved as of 14986

**Comment by bajjuri6** [comment]
This still doesn't work for me. Surface Pro 4 with FCU. 

I keep getting the same error message as in the original question on the thread.

Did something change in the FCU?

**Comment by michallepicki** [comment]
did you install inotify-tools in ubuntu?

**Comment by bajjuri6** [comment]
I just did. Doesn't seem to make a difference.

**Comment by jonnyasmar** [comment]
A few things that might help some of you:

1. Ensure you don't have the `poll` property set in your `watchOptions`.
2. You need to run WSL with elevation (run as administrator) in order for watching to work.

`Optional` You may also want to check if there are any other processes creating a lock on the files you're watching. I've noticed some pretty finicky behavior when running I/O on a file from both the WSL side & native.
