### ISSUE TITLE
ifconfig Warning: cannot open /proc/net/dev (No such file or directory). Limited output.

### ISSUE THREAD

**Issue by Mr-Hamdan** [Microsoft/BashOnWindows#602]
![image](https://cloud.githubusercontent.com/assets/20217800/16476209/ab201192-3e8d-11e6-933a-5b3b52385cf5.png)

**Comment by benhillis** [comment]
Thank you for reporting, this is the same underlying issue as #66 and #239.

**Comment by Mr-Hamdan** [comment]
thank you for the replay

may i ask you , when microsoft will fix this problem ?

regards

**Comment by odoland** [comment]
Same problem when using ifconfig

**Comment by bitcrazed** [comment]
Reopening since ifconfig is not fixed by the changes that enabled ping etc.

**Comment by DaveKZN** [comment]
I have just now (Aug 14) installed Windows 10 Anniversary Edition and enabled the Ubuntu Bash shell. I am able to run basic bash commands and it is able to update and install from the internet. But ifconfig returns `Warning: cannot open /proc/net/dev (No such file or directory). Limited output.`

**Comment by vaibhavbhalla** [comment]
For me sbin path was not included:
Command 'ifconfig' is available in '/sbin/ifconfig'
The command could not be located because '/sbin' is not included in the PATH environment variable.
This is most likely caused by the lack of administrative privileges associated with your user account.
ifconfig: command not found

after using: 
$ export PATH=$PATH:/sbin
getting: 
Warning: cannot open /proc/net/dev (No such file or directory). Limited output.

**Comment by ewan-fanduel** [comment]
Also having the above issue @vaibhavbhalla is experiencing 
```
ifconfig
Warning: cannot open /proc/net/dev (No such file or directory). Limited output.
```

**Comment by kimiazhu** [comment]
I have the same issue. and also the `ping` can not work properly.

```
$ ping google.com
ping: icmp open socket: Permission denied
```

**Comment by sandros87** [comment]
To solve the ping issue you need to start bash ad administrator

**Comment by rtosman** [comment]
ifconfig does not work, ping does.

**Comment by odoland** [comment]
It seems that WSL does not currently support this feature. Here is the user voice page to vote for prioritizing this issue:

https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/15202875-would-you-like-to-support-ifconfig-iw-iwconfig-t

**Comment by sunilmut** [comment]
Just FYI that starting build 14926, admin is no longer a requirement for ping/ping6 (thanks to the Windows networking team).

**Comment by mawadhwa** [comment]
Same problem while running ifconfig. Any update when can Microsoft fix this ?

**Comment by sunilmut** [comment]
Yes, we understand that `ifconfig` and similar tools such as `ip` currently don't work. We are looking into it, but no ETA at the moment. You can also voice your opinion at our [User Voice Page post](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/15202875-would-you-like-to-support-ifconfig-iw-iwconfig-t) for this and help us prioritize it. Thanks for your feedback!

**Comment by sunilmut** [comment]
Just an update that 'ifconfig' and the 'ip' commands for network enumeration should be working in the latest fast insider build 14965, also see [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes)

**Comment by timmy1337** [comment]
I fixed it. You need to reinstall bash and choose "root" as username. It's not very safe, but then 'ifconfig' is working. Just be patient ^^

**Comment by sunilmut** [comment]
Closing this out since this has been marked fixed for sometime. If the issue persists, please reopen.

**Comment by amaklp** [comment]
> I fixed it. You need to reinstall bash and choose "root" as username. It's not very safe, but then 'ifconfig' is working. Just be patient ^^

I chose "root" as username but I'm still getting the same warning.

**Comment by aseering** [comment]
@amaklp @timmy1337 -- choosing "root" as the username didn't help me.  `ifconfig` works on my machine as an ordinary (non-root) WSL user.  However, I did have to update to a recent Windows Insider build (I'm currently running build 14971).

**Comment by akapucu** [comment]
same problem here as well

**Comment by bitcrazed** [comment]
@akapucu You'll need to be running a build > 14965 for ifconfig or 14986 for ping to work. Essentially, install a current Insider build and you should be able to do both.

**Comment by Joshua-Cody** [comment]
same problem here as well.

**Comment by aseering** [comment]
@Joshua-Cody -- what Windows build are you running?  (Type `ver` at a Windows command prompt.)

The fix to this issue is currently only available to people who have subscribed to Windows [Insider builds](https://insider.windows.com/).  It's coming to stable Windows with the "Creators" update.

**Comment by linuxrooter** [comment]
I'm using termux and my permission /proc/net/dev is denied . How can I access it

**Comment by AjayKumar59** [comment]
I am face same problem , but after using WiFi or turn on hotspot , this problem solved

**Comment by GaN-u** [comment]
Its actually work

**Comment by oysqurany** [comment]
cannot open /proc/net/dev (Permission denied). Limited output.
ifconfig....solve this problem.

**Comment by Zarkoss-Zarkoss** [comment]
ifconfig cannot open /proc/net/dev (Permission denied kali linux problem

**Comment by unej474727zZ** [comment]
$ websploit
CRITICAL: Can't open /proc/net/dev !      CRITICAL: Can't open /proc/net/route !
CRITICAL: Can't open /proc/net/dev !

Only has to do root

**Comment by johncollinx** [comment]
Having the same issue in termux

**Comment by aswathparves** [comment]
Having the same issue in termux.
```
ifconfig
Warning: cannot open /proc/net/dev (No such file or directory). Limited output.
```

**Comment by Bhagat-Aadmi** [comment]
cannot open /proc/net/dev (Permission denied). Limited output.

**Comment by pepperhacker0124** [comment]
No fix yet huh
