### ISSUE TITLE
MySQL not creating mysqld.sock

### ISSUE THREAD

**Issue by Kansuler** [Microsoft/BashOnWindows#67]
The MySQL server installed by "apt-get install mysql-server" does not create any mysqld.sock file under /var/run/mysqld which makes it hard to connect to.

**Comment by SvenGroot** [comment]
Our support for Unix sockets is not yet complete, and they are currently not properly integrated with the file system. While mysqld does create a socket with the appropriate name and it should be possible to connect to it, it will not be visible in the file system.

**Comment by mobluse** [comment]
I get this error when i try to do **mysqladmin ping**:
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (13)'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
$

Starting it before seems to work: **sudo /etc/init.d/mysql start** or **sudo service mysql start**:
df: Warning: cannot read table of mounted file systems: No such file or directory
 * Starting MySQL database server mysqld                                         [ OK ]
 * Checking for tables which need an upgrade, are corrupt or were
not closed cleanly.

$

I couldn't start mysqld out of the box, but had to first fix according to https://github.com/Microsoft/BashOnWindows/issues/143 .

How do you connect to mysqld?

**Comment by abhishek1214** [comment]
I am facing similar issue. I have tried using the fixes from #143 but still I get the same error. It seems to be an issue with the socket implmentation for WSL. Can someone please provide me with a fix for this as I am unable to start mysql server on my WSL environment.

**Comment by paladox** [comment]
MYSQL works for me. All I did was apt-get install mysq* or if you want mariadb apt-get install mariadb*

**Comment by paladox** [comment]
You then sudo service MySQL start

**Comment by abhishek1214** [comment]
i ran sudo-apt get install mysql-server

E: Can not write log (Is /dev/pts mounted?) - openpty (2: No such file or directory)

I get this error while it is installing
and when i run sudo service mysql start i get the following errors. Did mysql run out of the box for you or did you make some fixes before.

df: Warning: cannot read table of mounted file systems: No such file or directory
 * Starting MySQL database server mysqld

**Comment by benhillis** [comment]
@abhishek1214 Both of these issues have been fixed internally and will be in a Windows Insider build soon.

**Comment by abhishek1214** [comment]
@benhillis are you referring to build 14342 or is there a new one coming soon. It would be great to have that as then I can move my dev environment completely to bash.

**Comment by benhillis** [comment]
I don't believe there fixes are in 14342. I'll check and get back to you.

**Comment by abhishek1214** [comment]
I just recieved the new Build 14352. Has this issue been resolved in the new update?

**Comment by ronaldroe** [comment]
Just tried it. Doesn't appear to be working yet. :(

**Comment by mattrunyon** [comment]
Any status update? Doesn't appear to be working on Build 14361

**Comment by abhishek1214** [comment]
Nope, its not working for me either. It was not mentioned in change log for build 14361, so was not expecting a change either. I wonder when this will be working..?

**Comment by SvenGroot** [comment]
This was fixed back in build 14342. I've just tried it on the latest insider release and it works fine for me. How are you installing/starting MySQL?

**Comment by abhishek1214** [comment]
I am installing using the sudo apt-get install mysql-server command. It throws an error which i have mentioned in the above post. its a error related to the sockets implementation for Bash on windows.

**Comment by ronaldroe** [comment]
Please, if we're doing something wrong when trying to install, let us know how to fix it.

**Comment by ronaldroe** [comment]
Error during install:
"E: Can not write log (Is /dev/pts mounted?) - openpty (2: No such file or directory)"

Error when trying to run basically anything related to mysql: 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by sunilmut** [comment]
pty and socket failures should be resolved in the last few Windows Insider builds 14361+. Which build are you on? Try upgrading to a newer build.

**Comment by sunilmut** [comment]
@ronaldroe - pty and socket failures should be resolved in the last few Windows Insider builds 14361+. Which build are you on? Try upgrading to a newer build.

**Comment by ronaldroe** [comment]
I'm trying on 14366, but I'm having another issue that's stopping me from trying. I opened another issue for it.

**Comment by ronaldroe** [comment]
Ok. That issue fixed, the pty error no longer shows up, but I still get the same error when I run mysql: 

"ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)"

I get this when I try to manually start the server service: 

/lib/lsb/init-functions.d/50-ubuntu-logging: line 5:   711 Aborted
    (core dumped) plymouth --ping > /dev/null 2>&1
 * Starting MySQL database server mysqld
/lib/lsb/init-functions.d/50-ubuntu-logging: line 5:  1445 Aborted
    (core dumped) plymouth --ping > /dev/null 2>&1
                                                                         [fail]

**Comment by paladox** [comment]
You should check your my.cnf file in /etc/mysql/my.cnf also try uninstalling MySQL and reinstalling it.

**Comment by ronaldroe** [comment]
Have tried both. No joy.

**Comment by paladox** [comment]
Oh, it worked for me from day one. Unless I changed something without realising. What does it say in /var/log/mysql/error.txt

**Comment by ronaldroe** [comment]
I get this multiple times during the install process: 
`invoke-rc.d: policy-rc.d denied execution of start.`

Error log is attached.

[error.txt](https://github.com/Microsoft/BashOnWindows/files/320873/error.txt)

**Comment by abhishek1214** [comment]
I recently received the 14367 update and have reinstalled the Linux subsystem with the /lxrun /uninstall /full method after the update. I have stopped getting the previous error but i am getting a new one now. it has some issue connecting to upstart..

initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
/lib/lsb/init-functions.d/50-ubuntu-logging: line 5:  1368 Aborted                 (core dumped) plymouth --ping > /dev/null 2>&1
 * Starting MySQL database server mysqld                                                                                                                                            /lib/lsb/init-functions.d/50-ubuntu-logging: line 5:  2088 Aborted                 (core dumped) plymouth --ping > /dev/null 2>&1

**Comment by paladox** [comment]
@ronaldroe it says this

ERROR: 1064  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE user ADD column Show_view_priv enum('N','Y') CHARACTER SET utf8 NOT ' at line 1
160519  7:58:32 [ERROR] Aborting

**Comment by paladox** [comment]
Do you have any MySQL or ports being used in windows not bash since windows can also interfear.

**Comment by abhishek1214** [comment]
yes i do. should i unistall that?

**Comment by ronaldroe** [comment]
You, sir are a baller. That was it. I had the Windows version running. Killing it allowed me to connect without issue. Thank you.

**Comment by abhishek1214** [comment]
I am still having the same problem i removed mysql from windows and i am still getting the same problem.

initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
runlevel:/var/run/utmp: No such file or directory

**Comment by benhillis** [comment]
@abhishek1214 We do not run the upstart init daemon.  Is there something you can configure so you don't attempt to connect to it?  I suspect there is because different versions of Linux use different init mechanisms.

**Comment by paladox** [comment]
@ronaldroe your welcome.

**Comment by paladox** [comment]
@abhishek1214 Hi what does it say in /var/log/mysql/error.txt.

**Comment by abhishek1214** [comment]
i just looked up online and found a solve which sad run atp-get remove upstream.

after that when i ran mysql server it stated working.

but error during the install is still there.

160617 23:42:15 [Note] Server socket created on IP: '127.0.0.1'.
160617 23:42:15 [Note] Event Scheduler: Loaded 0 events
160617 23:42:15 [Note] /usr/sbin/mysqld: ready for connections.
Version: '5.5.49-0ubuntu0.14.04.1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  (Ubuntu)

**Comment by sunilmut** [comment]
@SvenGroot - Did you run into this while trying out MySQL? It appeared that it was running fine for you.

**Comment by abhishek1214** [comment]
Yes i was able to run the server but there are some underlying issues with the implementation

For example: i was running a filter command in my python shell down an object tree and i was throw an error saying this function is not supported on this version of MySQL but i was able to run the commands on my mySQL command line. 

Also there are some network issues. I am not able to access the python server to the network port. So that i may access my server from my phone on the same wireless network.

Other than these things are running pretty smooth.

**Comment by benhillis** [comment]
After reading through this thread it looks like things are working as expected. Closing this out.

**Comment by markuszeller** [comment]
I simply could fix it with sudo
  service mysql start
  service mysql stop
  service mysql start

It looks like the database tables weren't created properly at the first launch.

**Comment by filjoseph1989** [comment]
I got this error for 1 week when trying to run `mysql -u root -p`

but when i try to run `sudo service mysql start`, it works fine

**Comment by vijay-stayntouch** [comment]
OK I think it has been already answered above but here I go again.

If you have installed mysql on the host Windows machine, the port is taken up by him. When you try to start mysql in WSL that mysql fail to start in the same port.

I uninstalled mysql from host and it all worked. Hope this works for you too!

**Comment by myvirtualteams** [comment]
i got errors while installing mysql-server on nginx server
how to solve this, anybody knows how to setup the mysql-server on the nginx
sudo service mysql start 
Job for mariadb.service failed because the control process exited with error code.
See "systemctl status mariadb.service" and "journalctl -xe" for details.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")

**Comment by a22375** [comment]
In my case it works, if I start mysql with

sudo /etc/init.d/mysql start

**Comment by abixalmon** [comment]
```
## Fix MySQL (MariaDB)
if [ ! -f "/etc/init.d/mysql" ]; then
    cp /usr/share/mysql/mysql.init /etc/init.d/mysql
    chmod a+x /etc/init.d/mysql
    service mysql restart
    mysql_secure_installation
    service mysql restart
fi
```

**Comment by sandren** [comment]
> 
> 
> For MariaDB 10.4
> 
> ```
> ## Fix MySQL (MariaDB)
> if [ ! -f "/etc/init.d/mysql" ]; then
>     cp /usr/share/mysql/mysql.init /etc/init.d/mysql
>     chmod a+x /etc/init.d/mysql
>     service mysql restart
>     mysql_secure_installation
>     service mysql restart
> fi
> ```

Thank you so much! 😀

**Comment by bidipeppercrap** [comment]
> For MariaDB 10.4
> 
> ```
> ## Fix MySQL (MariaDB)
> if [ ! -f "/etc/init.d/mysql" ]; then
>     cp /usr/share/mysql/mysql.init /etc/init.d/mysql
>     chmod a+x /etc/init.d/mysql
>     service mysql restart
>     mysql_secure_installation
>     service mysql restart
> fi
> ```

This fixes my problem!!!!!
Remember to use SUDO!

**Comment by baijifeilong** [comment]
> > For MariaDB 10.4
> > ```
> > ## Fix MySQL (MariaDB)
> > if [ ! -f "/etc/init.d/mysql" ]; then
> >     cp /usr/share/mysql/mysql.init /etc/init.d/mysql
> >     chmod a+x /etc/init.d/mysql
> >     service mysql restart
> >     mysql_secure_installation
> >     service mysql restart
> > fi
> > ```
> 
> This fixes my problem!!!!!
> Remember to use SUDO!

Worked for me too.

**Comment by ThaJay** [comment]
It only took me an hour to find this but THANKS 😃

**Comment by karlssonaufdemdach** [comment]
https://askubuntu.com/a/1194201/1011689

**Comment by gorazdzagar** [comment]
Hi, I know this is an old thread but has somebody come up with a good solution to the problem with custom MYSQLRUN folder creation? Let me explain the situation. 

We are running multiple instances of MySQL on a single node using the @ suffix in the config like:

[mysqld@3306]
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
datadir         = /var/lib/mysql

[mysqld@3307]
pid-file        = /var/run/mysqld-3307/mysqld.pid
socket          = /var/run/mysqld-3307/mysqld.sock
datadir         = /var/lib/mysql-3307

We use a custom path to the pid file and socket file and this requires us to create the folder (mysql-3307) manually as MySQL has a built in folder creation procedure in /usr/share/mysql-8.0/mysql-helpers. In section verify_ready(). Hardcoded path is used MYSQLRUN=/var/run/mysqld.

Now, we could modify this file to turn it into a variable or we could use ExecStart cmd in the systemd startup file. Either of which we do not want to modify as they are a part of the package and would require reset each time we upgrade,

The only solution for now I see that we rename just the socket and pid file but leave the folder as original. Any other ideas? Thanks.
