### ISSUE TITLE
Cannot install/run nodemon

### ISSUE THREAD

**Issue by davetropeano** [Microsoft/BashOnWindows#723]
`nodemon` is a common hot reloader for node applications. When I do an `npm install -g nodemon` I get the following:

```
npm WARN optional Skipping failed optional dependency /nodemon/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```

I am running node v6.3.1, and npm v3.10.3.

Even though `fsevents` is listed as optional when I run nodemon I get an error:

```
[nodemon] 1.10.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./bin/www`
[nodemon] Internal watch failed: watch /mnt/c/Users/Dave/dev/c2 EPERM
```

**Comment by dethoma** [comment]
This is likely dupe of #216 because we don't have inotify support plumbed yet. This is definitely on our list.

**Comment by YasharF** [comment]
Please vote here to get it fixed in Windows 10 Bash: https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13469097-support-for-filesystem-watchers-like-inotify

**Comment by bitcrazed** [comment]
This should now work in Windows 10 Insider builds >= [14942](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14942).

Closing here as this is also a dupe of #216

**Comment by YasharF** [comment]
Looking at the release notes at https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14942 the implementation isn't fully done yet.  More specifically, there is a correction to the release notes: "Correction: Inotify support for changes originating from Windows applications not available at this time."

The usecase that I am looking forward to get addressed is doing development using MS Visual Studio Code (in Windows), while having bash open with the (auto) compile and build tools (aka nodemon, etc).  The feature as described does not solve the problem for this usecase.

**Comment by computersarecool** [comment]
I am running the absolute latest version of Windows 10 (170424-221 atm) and I still have issues, in Bash as well I get:

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by OverStruck** [comment]
I'm getting this on Windows 10 1809 (Built: 17763.134)

`npm WARN optional Skipping failed optional dependency /react-scripts/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /webpack-dev-server/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none was installed.`
