### ISSUE TITLE
mv hangs

### ISSUE THREAD

**Issue by maverickg** [Microsoft/BashOnWindows#765]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description

After issuing ` mv x86_64-pc-linux-gnu-library/ x86_64-pc-linux-gnu-library2` from the command line, it hangs.   

What is more, even after I closes the Bash window, I cannot start a new one normally: the new one just shows nothing. 

* Expected results

Does the job very quickly and ends. 

* Actual results (with terminal output if applicable)

Nothings.  Even `Ctrl + C` cannot kill it. 

* Your Windows build number

14393.10 

* Steps / commands required to reproduce the error

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by onomatopellan** [comment]
Probably related to https://github.com/Microsoft/BashOnWindows/issues/650.
When a path ends with slash problem happens. It's already fixed but the fix didn't make it to Anniversary Update.

these should work
mv x86_64-pc-linux-gnu-library x86_64-pc-linux-gnu-library2
mv x86_64-pc-linux-gnu-library x86_64-pc-linux-gnu-library2/

**Comment by benhillis** [comment]
This has been fixed and the fix will be available once we start Windows Insider flighting,

**Comment by forresthopkinsa** [comment]
Still having this program now. `mv dir1/ dir2` and bash hung. The `mv` process was unkillable, and now even after restarting the computer Bash still won't open -- it just hangs for a minute and closes. I'm on "Release Preview" insider builds. Not sure if it would have an effect, but after Bash hung, I used Explorer to rename the directory properly.

**Comment by benhillis** [comment]
@forresthopkinsa - What is the Windows build number you're running.  You can check by running 'ver' in cmd.exe.

**Comment by forresthopkinsa** [comment]
@benhillis Hi, turns out I'm running the Anniversary Update still (14393.576), I guess that's the latest build in the Release Preview ring. Additionally, a second restart solved the problem. I still do think it strange that it wasn't fixed after the first restart... but it's fine now, so thanks

**Comment by benhillis** [comment]
@forresthopkinsa - Thanks for confirming. I'm currently working with the servicing team to see about backporting this fix as a Windows Update.

**Comment by forresthopkinsa** [comment]
@benhillis sounds good, thanks

**Comment by gmporter** [comment]
I'm running into this problem too, with mv hanging.  I'm running 10.0.14393.

**Comment by koying** [comment]
Any progress on this?
It quite limits the ability to build anything on the linux subsystem, as one of the autoconf checks if to see if "mv dir1/ dir2" works...

**Comment by aseering** [comment]
I believe this was fixed a while ago in [Insider builds](http://insider.windows.com).  Insider builds have a *lot* of major WSL fixes and improvements at this point.

If you can't or don't want to run an Insider build, WSL fixes in Insider builds are not being backported to existing stable Windows releases, but they will be in the next major stable Windows release (the "Creators" update).  I don't think the release date has been publicized, but if you look around online, you'll find many rumors that it's a couple months away from release.

**Comment by koying** [comment]
No "Windows Update" then? Too bad...
I'll wait.

**Comment by michael-ts** [comment]
I can't wait for this "Creators" update... I have just had to reboot windows 3 times in the last half hour because it's impossible to remember that such a horrible bug exists!

**Comment by whorfin** [comment]
How is a kernel deadlock not worthy of an update to Anniversary, ie "release build"?

**Comment by BlueBackbite** [comment]
Has this fix been implemented yet? It just happened to me. (build 14393.1198)

**Comment by aseering** [comment]
@BlueBackbite -- yes, it has been fixed in more-recent builds.  The latest stable Windows build (the "Creators" update) is build 15063, and it contains the fix.  If you're not getting that update through Windows Update, you can download it [here](https://www.microsoft.com/en-us/software-download/windows10).

**Comment by Armel2017** [comment]
Happened in Windows 10.0.16299.125 with : git mv

**Comment by aseering** [comment]
@Armel2017 -- thanks for reporting.  `git mv` is actually different in relevant ways than regular `mv`.  Specifically, there are large known slowdowns with git operations in some cases that occur because of git's history tracking, and which therefore don't affect regular filesystem commands.

Do you see this with regular `mv` as well?  If not, could you please file a new ticket with more information about how to reproduce the issue that you are seeing?  Specifically, in addition to your Windows build (from above), also whether you're seeing this in VolFS (/home, etc) or DrvFS (/mnt), and a link to an affected git repository if it is public.
